name: potta_pos
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  logging: ^1.3.0
  auto_route: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  iconsax_plus: ^1.0.0
  intl: ^0.20.2
  dio: ^5.0.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.1
  loading_animation_widget: ^1.3.0
  image_picker: ^1.1.2
  location: ^5.0.3
  flutter_screenutil: ^5.9.3
  wc_form_validators: ^1.2.0
  flutter_dotenv: ^5.2.1
  skeletonizer: ^2.1.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  auto_route_generator: ^8.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter


  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/logos/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

fluttergen:
  output: lib/src/generated
  line_length: 120

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: I18n
  main_locale: fr
  arb_dir: lib/src/core/i18n/l10n
  output_dir: lib/src/core/i18n
